# Generated by Django 3.0.7 on 2020-07-17 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0006_increase_name_max_length'),
        ('store', '0009_product_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='currencies.Currency'),
        ),
    ]
